import type { Passives } from '../types/passives.ts';

export const starterPassives = [
  'babyRattle',
  'breastplate',
  'reachersSpear',
  'etherealCloak',
  'everflowingGoblet',
  'crownOfThorns',
  'fleetFeet',
  'warHorn',
  'wretchedOnion',
  'deadeyesAmulet',
  'ghostlyCorset',
  'vampiricSword',
  'spikedCollar',
  'radiantFeather',
  'diamondHiltedDagger',
  'emeraldHiltedDagger',
  'rubyHiltedDagger',
  'sapphireHiltedDagger',
  'turret',
  'handFan',
  'swordBreaker',
  'handMirror',
  'loversQuiver',
  'silverBullet',
  'hourglass',
  'ironOnesie',
  'wretchedOnion',
  'ghostlyCorset',
] as const satisfies Passives[];
