import type { starterPassives } from '../constants/starterPassives.ts';

export type Passives =
  | 'babyRattle'
  | 'argentStopwatch'
  | 'arrowOfFate'
  | 'breastplate'
  | 'reachersSpear'
  | 'etherealCloak'
  | 'everflowingGoblet'
  | 'crownOfThorns'
  | 'fleetFeet'
  | 'warHorn'
  | 'wretchedOnion'
  | 'deadeyesAmulet'
  | 'ghostlyCorset'
  | 'fullMetalRapier'
  | 'handMirror'
  | 'hourglass'
  | 'ironOnesie'
  | 'loversQuiver'
  | 'silverBullet'
  | 'swordBreaker'
  | 'vampiricSword'
  | 'spikedCollar'
  | 'radiantFeather'
  | 'diamondHiltedDagger'
  | 'emeraldHiltedDagger'
  | 'rubyHiltedDagger'
  | 'sapphireHiltedDagger'
  | 'deadeyesCross'
  | 'turret'
  | 'handFan'
  | 'cornucopia'
  | 'odiferousShell'
  | 'graciousImpaler'
  | 'deadeyesImpaler'
  | 'grotesqueArtillery'
  | 'phantomRegalia'
  | 'soulReaver'
  | 'tormentorsMask'
  | 'wingsOfTheAnointed'
  | 'wretchedOnion'
  | 'ghostlyCorset';

export type StarterPassives = (typeof starterPassives)[number];
